### ISSUE TITLE
error on backing up

### ISSUE THREAD

**Issue by killmasta93** [rcarmo/imapbackup#19]
Hi 
Currently was trying to run the imapbackup.py but getting this error

Current command line

`python imapbackup.py --thunderbird -s mail.domain.com.com -u myemail@domain.com -p mypass  -e`

Thank you 

```
Finding Folders: 9 folders
Folder Archivo: 0 messages
File Archivo: 0 messages
New messages: 0
Folder Deleted Messages: 6 messages
File Deleted Messages: 135 messages
Downloading 6 new messages to Deleted Messages: 266.85 KB total, 55.41 KB for largest message
Folder Drafts: 9 messages
File Drafts: 9 messages
New messages: 0
Folder INBOX:
Traceback (most recent call last):
  File "imapbackup.py", line 792, in <module>
    main()
  File "imapbackup.py", line 713, in main
    (err, desc) = e
ValueError: need more than 1 value to unpack

```

**Comment by rcarmo** [comment]
Hi there!

That is a network error of some kind - there seems to be a bug here where it regards the way I’m unpacking the error message (most certainly due to the version of Python you’re using, since the script was written to work with older versions), but the line it is in points to it being a low-level socket error:

https://github.com/rcarmo/imapbackup/blob/master/imapbackup.py#L713 <https://github.com/rcarmo/imapbackup/blob/master/imapbackup.py#L713>

So before that error message is issued either the connection was dropped or unexpectedly closed. It is not an error related to the backups themselves, and can be ignored in that regard.

Since I can’t reproduce that sort of situation, I’d like to know what Python version you’re using so I can at least make sure that extracting the error description from the exception will work for you.

Thanks!

**Comment by killmasta93** [comment]
Thanks for the reply, Currently running these versions

```
root@prometheus:~# python --version
Python 2.7.13
root@prometheus:~# python3 --version
Python 3.5.3
```
But on the command line i run python without the number 3
